In [4]:
import numpy as np
a = np.array([1,2])
b = np.array([2,1])

z = np.log(a) 
print(z)

[0.         0.69314718]


In [2]:
z = np.exp(a)
print(z)

[2.71828183 7.3890561 ]


In [5]:
z = np.sqrt(a)
print(z)

[1.         1.41421356]


In [9]:
a = np.array([1,2])
b = np.array([2,4])
z = np.dot(a,b)
print(z)

10


In [10]:
z = a.dot(b)
print(z)

10


In [11]:
z = np.linalg.norm(a)
print(z)

2.23606797749979


In [12]:
z = np.linalg.norm(b)
print(z)

4.47213595499958


In [13]:
cosangle = a.dot(b) / np.linalg.norm(a) * np.linalg.norm(b)
print(cosangle)

20.000000000000004


In [14]:
angle = np.arccos(cosangle)
print(angle)

nan


c:\users\node\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arccos
  """Entry point for launching an IPython kernel.


In [15]:
a = np.matrix([[1,2,3],[4,5,6]])
print(a)
print(a[0,0])
x = np.array(a)
print(x)
print(x.T)

[[1 2 3]
 [4 5 6]]
1
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [16]:
z = np.zeros(5)
print(z)

m = np.zeros((2,2)) #5×5 matrix of zeros
print(m)
o = np.ones((3,3))
print(o)

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
r = np.random.random((2,2))
print(r)

[[0.32032649 0.38997182]
 [0.19376969 0.01661419]]


In [18]:
h = np.random.randn(2,2)
print(h)

[[ 0.03571146 -1.89840839]
 [-0.88358864 -0.45011347]]


In [19]:
print(h.mean())
print(h.var())

p = np.array([[1,2,3],[2,2,1],[6,7,9]])
q = np.array([[4,5],[6,7],[6,8]])

r = p.dot(q)
print(r)

-0.7990997618042265
0.50857976172256
[[ 34  43]
 [ 26  32]
 [120 151]]


In [20]:
pinv = np.linalg.inv(p)
print(pinv)

[[-1.57142857 -0.42857143  0.57142857]
 [ 1.71428571  1.28571429 -0.71428571]
 [-0.28571429 -0.71428571  0.28571429]]


In [21]:
correct = p.dot(pinv)
print(correct)

[[ 1.00000000e+00 -4.44089210e-16  1.11022302e-16]
 [-1.66533454e-16  1.00000000e+00  1.66533454e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [22]:
d = np.linalg.det(p)
print(d)

-7.000000000000004


In [23]:
di = np.diag(p)
print(di)

[1 2 9]


In [24]:
x = np.diag([1,2,3,4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [25]:
x = np.trace(x)
print(x)

10
